// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAau9gnhklSDPQXo9J6gzVgdy9QecyUUGc',
    appId: '1:1048843462577:web:e8a4102c643c81ff12ff90',
    messagingSenderId: '1048843462577',
    projectId: 'e-commerce-8161f',
    authDomain: 'e-commerce-8161f.firebaseapp.com',
    storageBucket: 'e-commerce-8161f.appspot.com',
    measurementId: 'G-75Q6FFVS72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8TYyP-myQcR7zPUSPlatgmG-ZXmSUFP0',
    appId: '1:1048843462577:android:6930019f44ae72f812ff90',
    messagingSenderId: '1048843462577',
    projectId: 'e-commerce-8161f',
    storageBucket: 'e-commerce-8161f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXF4o1Fq4A6XZNxagNQzcenk-DLoP8iW4',
    appId: '1:1048843462577:ios:dc25716a9d51a55b12ff90',
    messagingSenderId: '1048843462577',
    projectId: 'e-commerce-8161f',
    storageBucket: 'e-commerce-8161f.appspot.com',
    androidClientId: '1048843462577-fkddad72vauf0oqbessg39pfnj2p31rk.apps.googleusercontent.com',
    iosClientId: '1048843462577-qof00494o9l0sqomq8mnooa0isrmekk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXF4o1Fq4A6XZNxagNQzcenk-DLoP8iW4',
    appId: '1:1048843462577:ios:dc25716a9d51a55b12ff90',
    messagingSenderId: '1048843462577',
    projectId: 'e-commerce-8161f',
    storageBucket: 'e-commerce-8161f.appspot.com',
    androidClientId: '1048843462577-fkddad72vauf0oqbessg39pfnj2p31rk.apps.googleusercontent.com',
    iosClientId: '1048843462577-qof00494o9l0sqomq8mnooa0isrmekk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAau9gnhklSDPQXo9J6gzVgdy9QecyUUGc',
    appId: '1:1048843462577:web:008b48c1af0f1e0612ff90',
    messagingSenderId: '1048843462577',
    projectId: 'e-commerce-8161f',
    authDomain: 'e-commerce-8161f.firebaseapp.com',
    storageBucket: 'e-commerce-8161f.appspot.com',
    measurementId: 'G-LEP4D1HZNS',
  );
}
